[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info
user=root

[program:xvfb]
command=Xvfb :99 -screen 0 1080x1920x24 -ac +extension GLX
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:stream]
command=python3 /app/stream.py
autorestart=true
priority=20
startsecs=5
startretries=5
environment=DISPLAY=":99"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
